### ISSUE TITLE
Older sdk compatibility

### ISSUE THREAD

**Issue by LuisMCunha** [edsilfer/custom-searchable#2]
Hi Edgar,

Great work on the library, but unfortunately the current minSDK is prohibitively limiting. Could you perhaps reduce it to support something like api lvl 18 or even lower?
Thanks.

**Comment by edsilfer** [comment]
Hello @MoPHL , the issue has been solved in version 0.1.0-Beta. SOrry the time I took to do so, hope you still can use it.
